//! Render Temporal event attributes as structured JSON, including JSON payloads.
//! The descriptor set is generated by build.rs from the same pinned proto version
//! as the tonic client, so newly added event fields do not need handwritten UI code.
use crate::generated::temporal::api::history::v1::HistoryEvent;
use anyhow::{Context, Result};
use base64::{engine::general_purpose::STANDARD, Engine};
use prost::Message;
use prost_reflect::{DescriptorPool, DynamicMessage};
use serde_json::Value;
use std::sync::OnceLock;

fn descriptors() -> &'static DescriptorPool {
    static POOL: OnceLock<DescriptorPool> = OnceLock::new();
    POOL.get_or_init(|| {
        DescriptorPool::decode(
            include_bytes!(concat!(env!("OUT_DIR"), "/temporal_descriptor.bin")).as_slice(),
        )
        .expect("compiled Temporal protobuf descriptors are valid")
    })
}

/// Return the attributes of any Temporal event as indented JSON. Protobuf bytes
/// are base64 by default; decode only payloads explicitly marked JSON/plain.
pub fn structured_attributes(event: &HistoryEvent) -> Result<Vec<String>> {
    if event.attributes.is_none() {
        return Ok(vec!["No attributes available".into()]);
    }
    let descriptor = descriptors()
        .get_message_by_name("temporal.api.history.v1.HistoryEvent")
        .context("Temporal history event descriptor missing")?;
    let dynamic = DynamicMessage::decode(descriptor, event.encode_to_vec().as_slice())?;
    let mut value = serde_json::to_value(dynamic)?;
    let attributes = value
        .as_object_mut()
        .and_then(|object| {
            let key = object
                .keys()
                .find(|key| key.ends_with("EventAttributes"))?
                .clone();
            object.remove(&key)
        })
        .context("Temporal event attributes missing from decoded event")?;
    let mut attributes = attributes;
    decode_payloads(&mut attributes);
    let pretty = serde_json::to_string_pretty(&attributes)?;
    Ok(pretty.lines().map(str::to_owned).collect())
}

fn decode_payloads(value: &mut Value) {
    match value {
        Value::Array(values) => values.iter_mut().for_each(decode_payloads),
        Value::Object(object) => {
            if let Some(metadata) = object.get_mut("metadata").and_then(Value::as_object_mut) {
                for metadata_value in metadata.values_mut() {
                    if let Some(base64) = metadata_value.as_str() {
                        if let Ok(bytes) = STANDARD.decode(base64) {
                            if let Ok(text) = String::from_utf8(bytes) {
                                *metadata_value = Value::String(text);
                            }
                        }
                    }
                }
            }
            let encoding = object
                .get("metadata")
                .and_then(|metadata| metadata.get("encoding"))
                .and_then(Value::as_str);
            if let Some(encoded) = object.get("data").and_then(Value::as_str) {
                if let Ok(bytes) = STANDARD.decode(encoded) {
                    let decoded = match encoding {
                        Some("json/plain") => serde_json::from_slice(&bytes).ok(),
                        Some("binary/plain") => String::from_utf8(bytes).ok().map(Value::String),
                        _ => None, // Keep unknown/encrypted encodings as base64.
                    };
                    if let Some(decoded) = decoded {
                        object.insert("data".into(), decoded);
                    }
                }
            }
            // Any payload nested in an input, result or failure is handled too.
            for (key, child) in object.iter_mut() {
                if key != "metadata" && key != "data" {
                    decode_payloads(child);
                }
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generated::temporal::api::{
        common::v1::{Payload, Payloads},
        history::v1::{
            history_event::Attributes, WorkflowExecutionCompletedEventAttributes,
            WorkflowExecutionStartedEventAttributes,
        },
    };
    use std::collections::HashMap;

    #[test]
    fn started_event_formats_nested_input_as_json() {
        let event = HistoryEvent {
            event_id: 1,
            attributes: Some(Attributes::WorkflowExecutionStartedEventAttributes(
                WorkflowExecutionStartedEventAttributes {
                    input: Some(Payloads {
                        payloads: vec![Payload {
                            metadata: HashMap::from([("encoding".into(), b"json/plain".to_vec())]),
                            data: br#"{"order":42,"items":["a","b"]}"#.to_vec(),
                            ..Default::default()
                        }],
                    }),
                    ..Default::default()
                },
            )),
            ..Default::default()
        };
        let text = structured_attributes(&event).unwrap().join("\n");
        assert!(text.contains("\"encoding\": \"json/plain\""), "{text}");
        assert!(text.contains("\"order\": 42"), "{text}");
        assert!(text.contains("\"items\": ["), "{text}");
        assert!(!text.contains("[123, 34"), "{text}");
    }

    #[test]
    fn completion_result_is_structured_too() {
        let event = HistoryEvent {
            attributes: Some(Attributes::WorkflowExecutionCompletedEventAttributes(
                WorkflowExecutionCompletedEventAttributes {
                    result: Some(Payloads {
                        payloads: vec![Payload {
                            metadata: HashMap::from([("encoding".into(), b"json/plain".to_vec())]),
                            data: br#"{"success":true,"count":3}"#.to_vec(),
                            ..Default::default()
                        }],
                    }),
                    ..Default::default()
                },
            )),
            ..Default::default()
        };
        let text = structured_attributes(&event).unwrap().join("\n");
        assert!(text.contains("\"result\": {"), "{text}");
        assert!(text.contains("\"success\": true"), "{text}");
        assert!(text.contains("\"count\": 3"), "{text}");
    }

    #[test]
    fn unknown_payload_encoding_stays_base64() {
        let data = b"\0\x01\x02";
        let mut value = serde_json::json!({
            "metadata": { "encoding": STANDARD.encode("binary/custom") },
            "data": STANDARD.encode(data),
        });
        decode_payloads(&mut value);
        assert_eq!(value["metadata"]["encoding"], "binary/custom");
        assert_eq!(value["data"], STANDARD.encode(data));
    }

    #[test]
    fn missing_attributes_are_explicit() {
        assert_eq!(
            structured_attributes(&HistoryEvent::default()).unwrap(),
            vec!["No attributes available"]
        );
    }
}
